### ISSUE TITLE
Application Header

### ISSUE THREAD

**Issue by gorkemmulayim** [Bil496/StudifyApp#4]
Application header element represents a container for introductory content or a set of navigational links.
Application header will be visible to user all the time but the context will vary depending on the situation.

There is a dropdown menu on the left hand side of the header. If the user is not logged in:
* Login
* Sign in

links should be visible when dropdown menu is opend.

If the user is logged in:
* Home
* Groups
* Profile
* Logout

links will be provided.

**Comment by theonuryildiz** [comment]
We can design login/signup part without dropdown menu.

**Comment by theonuryildiz** [comment]
Side Menu completed. There wont be any in the login/signup page so header is completed.
