### ISSUE TITLE
Group Search Page

### ISSUE THREAD

**Issue by gorkemmulayim** [Bil496/StudifyApp#5]
Search page is used to list groups that are found by search.
User is asked to fill below fields:
* Group topics (at least one)
* Group locations (at least one)
* Group score (optional)

Group topics are list that contains topics entered by the user.
Group locations are list that contains locations entered by the user.
User is able to add/remove topics/locations in the lists.

After searching, found groups will be listed to user if any. User can click participate button that is next to each found group to participate in that group. If the user is already participated in that group he/she participate is replaced with unparticipate button.

**Comment by theonuryildiz** [comment]
Also user should be able to navigate Group's Profile Page. To see attendees, detailed info etc.
